language: go

go:
  - 1.7


before_install:
  - mkdir -p /home/travis/gopath/bin
  - curl https://glide.sh/get | sh
  - make dep_install
  - ls vendor

script:
  - make test

cache:
  directories:
  - vendor
